name: Terragrunt Plan
description: Runs terragrunt plan step

inputs:
  workingDirectory:
    description: Directory to run terragrunt commands
    required: true
  environment:
    description: Environment name (e.g., dev, prod)
    required: true
  parallelism:
    description: Number of parallel operations
    required: false
    default: '10'
  tflog:
    description: Terraform log level
    required: false
    default: 'ERROR'

runs:
  using: "composite"
  steps:
    - name: Terragrunt Plan
      shell: bash
      env:
        TF_LOG: ${{ inputs.tflog }}
        PARALLELISM: ${{ inputs.parallelism }}
      run: |
        cd "${{ inputs.workingDirectory }}"
        terragrunt plan --terragrunt-source-update -out=tfplan.out -- -parallelism=${{ inputs.parallelism }}