name: Build and Push Docker Image with Kaniko

inputs:
  dockerfile:
    required: true
  context:
    required: true
  registry:
    required: true
  image:
    required: true
  tag:
    required: true
  push:
    required: false
    default: "false"
  verbose:
    required: false
    default: "info"

runs:
  using: "composite"
  steps:
    - name: Build and Push Image
      shell: bash
      run: |
        if [ "${{ inputs.push }}" == "true" ]; then
          /kaniko/executor \
            --dockerfile=${{ inputs.dockerfile }} \
            --context=${{ inputs.context }} \
            --destination=${{ inputs.registry }}/${{ inputs.image }}:${{ inputs.tag }} \
            --skip-tls-verify --verbosity=${{ inputs.verbose }} --snapshot-mode=redo --single-snapshot --ignore-path=/ --ignore-path=/home/runner --cleanup=false
        else
          /kaniko/executor \
            --dockerfile=${{ inputs.dockerfile }} \
            --context=${{ inputs.context }} \
            --destination==${{ inputs.registry }}/${{ inputs.image }}:${{ inputs.tag }} \
            --no-push --verbosity=${{ inputs.verbose }} --single-snapshot --ignore-path=/ --ignore-path=/home/runner --cleanup=false
        fi
        echo " Image is successfully pushed to the artifactory"
        exit 0