name: Uninstall Helm Release

description: Uninstall (delete) a Helm release from a Kubernetes cluster

inputs:
  release:
    description: 'Helm release name'
    required: true
  namespace:
    description: 'Kubernetes namespace'
    required: true
  helm_opts:
    description: 'Extra options to pass to the helm uninstall command (optional)'
    required: false

runs:
  using: "composite"
  steps:
    - name: Helm Uninstall
      shell: bash
      run: |
        helm uninstall ${{ inputs.release }} --namespace ${{ inputs.namespace }} ${{ inputs.helm_opts || '' }}
