name: Terragrunt Format
description: Runs terragrunt format step

inputs:
  workingDirectory:
    description: Directory to run terragrunt commands
    required: true
  environment:
    description: Environment name (e.g., dev, prod)
    required: true
  tflog:
    description: Terraform log level
    required: false
    default: 'ERROR'

runs:
  using: "composite"
  steps:
    - name: Terragrunt Format
      shell: bash
      env:
        TF_LOG: ${{ inputs.tflog }}
        PARALLELISM: ${{ inputs.parallelism }}
      run: |
        cd "${{ inputs.workingDirectory }}"
        terragrunt apply tfplan.out --terragrunt-non-interactive