name: helm-uninstall-reusable

on:
  workflow_call:
    inputs:
      runner:
        description: "Name of the GH runner"
        required: false
        type: string
        default: "nonprod-linux-x64-medium"
      project_id:
        description: "GCP Project ID"
        required: false
        type: string
      region:
        description: "GCP Region"
        required: false
        type: string
        default: us-east4
      cluster:
        description: 'GKE Cluster name'
        required: true
        type: string
      release:
        description: "Helm release name"
        required: true
        type: string
      namespace:
        description: "Kubernetes namespace"
        required: true
        type: string
      helm_opts:
        description: "Extra options to pass to the helm command (optional)"
        required: false
        type: string

jobs:
  uninstall:
    runs-on: ${{ inputs.runner }}
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: GCP Auth
        uses: girishcodealchemy/gh-actions-alchemy-library/.github/actions/gcp/auth@main
        with:
          project_id:  ${{ inputs.project_id || secrets.GCP_NONPROD_PROJECT_ID }}
          workload_identity_provider: ${{ inputs.workload_identity_provider || secrets.GCP_NONPROD_WORKLOAD_IDENTITY_PROVIDER }}

      - name: Get GKE Credentials
        shell: bash
        run: |
          gcloud container clusters get-credentials ${{ inputs.cluster }} --region ${{ inputs.region }} --project ${{ inputs.gcp_project_id || secrets.GCP_NONPROD_PROJECT_ID }}

      - name: Uninstall Helm Release
        uses: girishcodealchemy/gh-actions-alchemy/.github/actions/k8s/helm/uninstall@main
        with:
          release: ${{ inputs.release }}
          namespace: ${{ inputs.namespace }}
          helm_opts: ${{ inputs.helm_opts }}
