name: Terragrunt Action Workflow Test


on:
 workflow_call:
   inputs:
    runner:
      description: "Name of the GH runner"
      required: false
      type: string
      default: "nonprod-linux-x64-medium"
    workingDirectory:
      description: "Path to the working directory"
      required: true
      type: string
    environment:
      description: "Name of the environment"
      required: true
      type: string
    tfLog:
      description: Terraform log level
      required: false
      type: string
      default: 'ERROR'

jobs:
  terragrunt-job:
    runs-on: ${{ inputs.runner }}
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      TERRAGRUNT_GITHUB_ORG_TOKEN: ${{ secrets.TERRAGRUNT_GITHUB_ORG_TOKEN }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Terragrunt Init
      uses: girishcodealchemy/gh-actions-alchemy-library/.github/actions/terragrunt/init@main
      with:
        workingDirectory: ${{ inputs.workingDirectory }}
        environment: ${{ inputs.environment }}
        tfLog: ${{ inputs.tfLog }}


    - name: Terragrunt Validate
      uses: girishcodealchemy/gh-actions-alchemy-library/.github/actions/terragrunt/validate@main
      with:
        workingDirectory: ${{ inputs.workingDirectory }}
        environment: ${{ inputs.environment }}
        tfLog: ${{ inputs.tfLog }}

    - name: Terragrunt Lint
      uses: girishcodealchemy/gh-actions-alchemy-library/.github/actions/terragrunt/lint@main
      with:
        workingDirectory: ${{ inputs.workingDirectory }}
        environment: ${{ inputs.environment }}
        tfLog: ${{ inputs.tfLog }}

    - name: Terragrunt Plan
      uses: girishcodealchemy/gh-actions-alchemy-library/.github/actions/terragrunt/plan@main
      with:
        workingDirectory: ${{ inputs.workingDirectory }}
        environment: ${{ inputs.environment }}
        tfLog: ${{ inputs.tfLog }}

    - name: Upload TF Plan
      uses: actions/upload-artifact@v4
      with:
        name: tf-plan
        path: ${{ github.workspace }}/${{ inputs.workingDirectory }}/tfplan.out
        retention-days: 30

  terragrunt-apply:
    needs: terragrunt-plan
    environment: nonprod
    runs-on: ${{ inputs.runner }}
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      TERRAGRUNT_GITHUB_ORG_TOKEN: ${{ secrets.TERRAGRUNT_GITHUB_ORG_TOKEN }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: GCP Auth
      uses: girishcodealchemy/gh-actions-alchemy-library/.github/actions/gcp/auth@main
      with:
        project_id:  ${{ secrets.GCP_NONPROD_PROJECT_ID }}
        workload_identity_provider: ${{ secrets.GCP_NONPROD_WORKLOAD_IDENTITY_PROVIDER }}
      
    - name: Download TF Plan
      uses: actions/download-artifact@v4
      with:
        name: tf-plan
        path:  ${{ inputs.workingDirectory }}

    - name: Terragrunt Apply
      if: github.ref == 'refs/heads/main'
      uses: girishcodealchemy/gh-actions-alchemy-library/.github/actions/terragrunt/apply@main
      with:
        workingDirectory: ${{ inputs.workingDirectory }}
        environment: ${{ inputs.environment }}
        tfLog: ${{ inputs.tfLog }}