name: Terragrunt Action Workflow Test


on:
 workflow_call:
   inputs:
    runner:
      description: "Name of the GH runner"
      required: false
      type: string
      default: "nonprod-linux-x64-medium"
    workingDirectory:
      description: "Path to the working directory"
      required: true
      type: string
    environment:
      description: "Name of the environment"
      required: true
      type: string

jobs:
 terragrunt-job:
    runs-on: ${{ inputs.runner }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Terragrunt Init
      uses: girishcodealchemy/gh-actions-alchemy-library/.github/actions/terragrunt/init@main
      with:
        workingDirectory: terragrunt-noop-module
        environment: nonprod


    - name: Terragrunt Validate
      uses: girishcodealchemy/gh-actions-alchemy-library/.github/actions/terragrunt/validate@main
      with:
        workingDirectory: terragrunt-noop-module
        environment: nonprod

    - name: Terragrunt Lint
      uses: girishcodealchemy/gh-actions-alchemy-library/.github/actions/terragrunt/lint@main
      with:
        workingDirectory: terragrunt-noop-module
        environment: nonprod

    - name: Terragrunt Plan
      uses: girishcodealchemy/gh-actions-alchemy-library/.github/actions/terragrunt/plan@main
      with:
        workingDirectory: terragrunt-noop-module
        environment: nonprod

    - name: Terragrunt Apply
      uses: girishcodealchemy/gh-actions-alchemy-library/.github/actions/terragrunt/apply@main
      with:
        workingDirectory: terragrunt-noop-module
        environment: nonprod